---
author: Gregory M. Kapfhammer
title: SEED Interview with Rebecca Dilla
date: '2018-01-01'
date-format: YYYY
categories: [post, industry connections, seed interview]
description: <em>Let's learn from Rebecca Dilla!</em>
aliases: ["/seed/interview/software/2017/09/11/SEED-Rebecca-Dilla/"]
company_name: "Niche.com"
title_name: "Product Analyst"
web_site: "https://www.linkedin.com/in/rebecca-dilla-ab174974/"
---

## SEED Interview

As part of the [SEED project](/blog/introducing-seed-survey/index.qmd), I
recently talked with [Rebecca Dilla]({{< meta web_site >}}), a {{< meta
title_name >}} at {{< meta company_name >}}. In this interview, Rebecca told me
that students should consider the benefits of working in small companies. She
also stressed the importance of professional networking, encouraging people to
reach out to others with questions and requests for assistance. Read Rebecca's
responses to the three SEED questions to learn more about her unique perspective
on software engineering.

### What is one fun fact that you can share about your company or a current project?

> My company is tiny, but powerful! We've only got about 30 people in our office,
> but we get a lot work done &mdash; and have good time together! Niche has a
> great work/life balance. We have a soccer team, breakfast club, and a reading
> club. While we love making our product, we also realize that what you do from
> nine to five isn't the most important part of your life.

### What is the greatest challenge that you face when working in your field?

> There are never enough hours in the day to make the product you would love to
> make! In school, your work is done when you turn your project in. But, in
> industry, the product is never "done". It's continually being fixed, grown, and
> improved.

### What is one point of advice that you can give to people who plan to enter your field?

> Don't just look at the big companies when you're looking for a job. Ask around,
> talk to people. Often, there are so many benefits to working for a smaller
> company, including a bigger chance to make an impact. The downside is that they
> are harder to find &mdash; this is where networking comes in so handy. Invite an
> acquaintance in the field out to coffee so that you can ask them a few
> questions. If you currently don't have any contacts, reach out to some people
> you've found online. It's scary, but it'll give you better insight and teach you
> about opportunities you never knew existed.

::: {.callout-note appearance="simple"}

## Further Details

Do you have any questions about this interview? Or, do you have a response to
Rebecca's ideas? If you do, then I hope that you will [contact](/contact/) me to
share some of your thoughts. Or, do you want to be updated when I publish new
interviews? If you do, then please [subscribe](/support/) to my
mailing list.

:::

{{< include /_back-blog.qmd >}}
