---
title: "Gregory M. Kapfhammer"
echo: true
jupyter: python3
section-divs: true
keep-md: false
toc: true
page-layout: full
title-block-style: default
title-block-banner: false
format:
  html:
    include-in-header:
      file: _include/js/mastodon-timeline.js
listing:
  - id: featured-papers
    contents:
      - "research/papers/**"
      - "!research/papers/index.qmd"
    sort:
      - "date desc"
      - "author title categories"
    type: default
    date-format: "YYYY"
    sort-ui: false
    filter-ui: false
    fields: [author, date, title, description]
    max-items: 5
    page-size: 5
  - id: featured-presentations
    contents:
      - "research/presentations/**"
      - "!research/presentations/index.qmd"
    sort:
      - "date desc"
      - "author title categories"
    type: default
    date-format: "YYYY"
    sort-ui: false
    filter-ui: false
    fields: [author, date, title, description]
    max-items: 5
    page-size: 5
  - id: featured-posts
    contents:
      - "blog/**/*.qmd"
      - "!blog/index.qmd"
    sort:
      - "date desc"
      - "title"
      - "author categories"
    type: default
    date-format: "YYYY"
    sort-ui: false
    filter-ui: false
    fields: [author, title, date, description, reading-time]
    max-items: 5
    page-size: 5
  - id: featured-service
    contents:
      - "service/**/*.qmd"
      - "!service/index.qmd"
      - service.yml
    sort:
      - "date desc"
      - "year-range desc"
      - "title"
    type: table
    categories: false
    date-format: "YYYY"
    sort-ui: false
    filter-ui: false
    fields: [title, description, year-range]
    field-display-names:
      description: "Role(s)"
      title: "Venue"
      year-range: "Year(s)"
    field-links: []
    max-items: 5
    page-size: 5
  - id: featured-media
    contents:
      - media.yml
    sort:
      - "date desc"
      - "title"
    type: table
    categories: false
    date-format: medium
    sort-ui: false
    filter-ui: false
    fields: [title, venue, description]
    field-display-names:
      title: "Event"
      venue: "Venue"
      description: "Role"
    field-links: []
    max-items: 5
    page-size: 5
# execute:
#   freeze: auto
---

```{python}
from rich.console import Console
console = Console()
console.print(
    ":rocket: Hi! I'm a researcher, teacher, and software developer!"
)
```

Innovating in technical areas such as software engineering and software testing,
I teach [courses](teaching/index.qmd), conduct [research](research/index.qmd),
write [papers](research/papers/index.qmd) and a [blog](blog/index.qmd), give
[presentations](research/presentations/index.qmd), create
[software](software/index.qmd), and [serve](service/index.qmd) organizations.
Working as an Associate Professor in the [Department of Computer and Information
Science](https://www.cis.allegheny.edu/) at [Allegheny
College](http://www.allegheny.edu), I am an associate editor for the [Journal of
Software: Evolution and
Process](https://onlinelibrary.wiley.com/journal/20477481), an academic editor
for the [PeerJ Computer Science](https://peerj.com/computer-science/) journal, a
program committee member for conferences like the [International Conference on
Software Testing, Verification and
Validation](https://cs.gmu.edu/icst/index.html) and the [International
Conference on Software Engineering](https://conf.researchr.org/series/icse), and
a reviewer for journals like [Transactions on Software
Engineering](https://www.computer.org/csdl/journal/ts) and the [Journal of
Software Testing, Verification and
Reliability](https://onlinelibrary.wiley.com/journal/10991689). You can learn
more about me and my work by reading my [biography](biography/index.qmd),
downloading my [curriculum
vitae](https://github.com/gkapfham/curriculum-vitae/releases/download/v1.4.0/curriculum_vitae_kapfhammer.pdf),
and [subscribing](support/index.qmd) to my mailing list.

## Research Expertise

- [Database Testing](research/index.qmd#database-testing): Automatically test
relational database schemas

- [Flaky Tests](research/index.qmd#flaky-tests): Find and fix unpredictable and
harmful test cases

- [Mutation Testing](research/index.qmd#mutation-testing): Using automatically
seeded defects to evaluate tests

- [Regression Testing](research/index.qmd#regression-testing): Efficiently and
effectively rerunning test suites

- [Web Testing](research/index.qmd#web-testing): Detecting and repairing
  responsive web page layout

::: {.callout-tip appearance="minimal"}

{{< fa rocket >}} <em>Explore</em> all of my areas of [research expertise](research/index.qmd)

:::

## Featured Papers

:::{#featured-papers}
:::

::: {.callout-tip appearance="minimal"}

{{< fa rocket >}} <em>Read</em> all of my  [research papers](research/papers/index.qmd)

:::

## Featured Presentations

:::{#featured-presentations}
:::

::: {.callout-tip appearance="minimal"}

{{< fa rocket >}} <em>Review</em> all of my [research presentations](research/presentations/index.qmd)

:::

## Professional Service

:::{#featured-service}
:::

::: {.callout-tip appearance="minimal"}

{{< fa rocket >}} <em>Investigate</em> all of my [professional service](service/index.qmd)

:::

## Recent Posts

:::{#featured-posts}
:::

::: {.callout-tip appearance="minimal"}

{{< fa rocket >}} <em>Read</em> all of my [blog posts](blog/index.qmd)

:::

## Media Appearances

:::{#featured-media}
:::

::: {.callout-tip appearance="minimal"}

{{< fa rocket >}} <em>Learn</em> more by reading my [professional biography](biography/index.qmd)

:::

## Highlighted Courses

- [Algorithm Analysis](https://www.algorithmology.org): Implement and evaluate
correct and efficient algorithms

- [Data
Abstraction](https://proactiveprogrammers.com/data-abstraction/introduction-data-abstraction/):
Build and manipulate correct and efficient data structures

- [Discrete
Structures](https://proactiveprogrammers.com/discrete-structures/introduction-discrete-structures/):
Clearly connect mathematics to Python programming

- [Operating Systems](https://www.os-sketch.com/): Build and understand operating system components

- [Software Engineering](https://developerdevelopment.com/): Team-based
introduction to building software systems

::: {.callout-tip appearance="minimal"}

{{< fa rocket >}} <em>Explore</em> all of my [teaching materials](teaching/index.qmd)

:::

## Software Engineering

<ul>

<li><p><a target="_blank" rel="noopener"
href="https://github.com/GatorEducator/cellveyor">Cellveyor</a>: Easily convey
reports from Google Sheets to GitHub</p></li>

<li><p><a target="_blank" rel="noopener"
href="https://github.com/AstuteSource/chasten">Chasten</a>: Configurable
linting tool that uses XPath expressions</p></li>

<li><p><a target="_blank" rel="noopener"
href="https://github.com/GatorEducator/gatorgrade">GatorGrade</a>: Python
front-end for the GatorGrader assessment tool</p></li>

<li><p><a target="_blank" rel="noopener"
href="https://github.com/GatorEducator/gatorgrader">GatorGrader</a>: Automated
assessment for source code and writing</p></li>

<li><p><a target="_blank" rel="noopener"
href="https://github.com/schemaanalyst-team/schemaanalyst">SchemaAnalyst</a>:
Data generation and mutation analysis for database schemas</p></li>

</ul>


::: {.callout-tip appearance="minimal"}

{{< fa rocket >}} <em>Benefit</em> from my open-source [software](software/index.qmd)

:::

## Status Updates

```{=html}
<div class="dummy-container">
	<div class="mt-timeline">
		<div id="mt-body" class="mt-body" role="feed">
		  <div class="loading-spinner"></div>
		</div>
  </div>
</div>
```
