---
title: Schedule
echo: true
jupyter: python3
---

```{python}
from rich.console import Console
console = Console()
console.print(
    ":calendar: My schedule is often full - but I look forward to our meeting!"
)
```

## Overview

To arrange a meeting with me during my office hours, please try to <a
href="https://calendar.app.google/oNetMoRQcawCLEsy8">Schedule
an Appointment</a>&mdash;you can browse my available office hours and pick a
time slot that fits into our schedules. Once you have chosen your appointment,
it will appear in both your Google Calendar and mine. If you would like to see
where I am during any week of the academic semester, you may <a
href="http://www.google.com/calendar/embed?src=gkapfham%40allegheny.edu&ctz=America/New_York">View
My Calendar</a>&mdash;but please note that my schedule is not regularly updated
during any of <a href="http://www.allegheny.edu">Allegheny College</a>'s breaks
that are documented in the <a href =
"http://sites.allegheny.edu/dean/academic-calendar/">Academic Calendar</a>.

## Considerations

Individuals seeking to schedule an appointment with me should also bear in mind
that I have previously scheduled teaching, mentoring, research, and
administrative events that may prevent me from either holding office hours
beyond those normally scheduled or agreeing to extra meetings outside of
existing office hours. As such, I greatly appreciate your understanding of my
circumstances when I must decline a meeting due to schedule constraints.

## Schedule

You can [schedule an
appointment](https://calendar.app.google/oNetMoRQcawCLEsy8) or schedule one with the
following embedded widget!

<!-- Google Calendar Appointment Scheduling begin -->
<iframe src="https://calendar.google.com/calendar/appointments/schedules/AcZssZ1_eRi6JBQbgNBmihMrp9qr5_XL2nWQn9HnL3R0rsB9e4YyteKd6EgYdG0ZQ0svomGOMBvuhFbA?gv=true" style="border: 0" width="100%" height="600" frameborder="0"></iframe>
<!-- end Google Calendar Appointment Scheduling -->
