---
author: Gregory M. Kapfhammer
title: Streamlining database application testing with STICCER
date: '2020-01-01'
date-format: YYYY
categories: [post, database testing, empirical study]
description: <em>How can we quickly test database applications?</em>
---

## Introduction

Are you tired of the time-consuming processes associated with testing database
schemas? Our latest research published in [@Alsharif2020] [{{< iconify fa6-solid
book-open >}}](/research/papers/alsharif2020/index.qmd) introduces STICCER, a 
technique designed to enhance the way you approach database test suite
reduction. 

## Insights

Here are some of the key insights from this paper:

- **Automated Efficiency**: STICCER intelligently identifies and merges similar
test cases, significantly reducing the size of your test suite without
compromising coverage.
   
- **Enhanced Speed**: Our experiments with 34 real-world relational database
schemas revealed that STICCER can make test suites up to 5 times faster than the
original, and 2.5 times faster compared to traditional reduction methods.

- **Maintained Effectiveness**: Despite the reduction in the number of tests,
STICCER ensures that the effectiveness of the test suite is preserved, with
minimal impact on fault detection.

- **Real-World Application**: Whether you’re working with SQLite, PostgreSQL, or
transitioning between different DBMSs, STICCER adapts to your needs, maintaining
the integrity and consistency of your relational database through an approach to
efficient schema testing.

## Future

By leveraging STICCER, you can streamline your database testing process,
ensuring faster and more efficient testing cycles. Please read the full paper to
explore the full potential of STICCER and stay ahead in the field of database
testing! You can try out STICCER with the
[schemaanalyst](https://github.com/schemaanalyst-team/schemaanalyst) tool and
replicate this paper's empirical results by using the
[sticcer-replicate](https://github.com/schemaanalyst/sticcer-replicate) package.

::: {.callout-note appearance="simple"}

## Further Details

If you have ideas on how to refine this test suite reduction method for database
applications, please [contact](/contact/) me! Furthermore, if you wish to stay
informed about new developments and blog posts related to STICCER and other
similar topics, please consider [subscribing](/support/) to my mailing list.

:::

{{< include /_back-blog.qmd >}}
