---
author: Gregory M. Kapfhammer
title: "Introducing SEED: Educational discussions with software engineers"
date: '2017-01-01'
date-format: YYYY
categories: [post, seed interviews, industry connections]
description: <em>Let's have educational discussions with industry!</em>
aliases: ["/seed/interview/software/2017/07/05/Introducing-SEED/"]
---

Do you work in the software industry? Are you interested in sharing your
knowledge and experiences with up-and-coming members of your field? Do you want
to influence the way academics teach and conduct research? If so, then please
allow me to interview you through the [SEED survey](/seed/).
Want to learn more about this initiative? If yes, then keep reading this post.

I am an educator who frequently teaches courses in areas like software
engineering. While I am an active [researcher](/research/) and I
[teach](/teaching/) courses in a wide variety of areas and contribute to
numerous [software](/software/) projects, I do not currently work full-time in
the software industry. Although I do everything possible to ensure that my
teaching and research are practically applicable, I would like to engage with
professionals in the software field so that I can do an even better job. I want
to improve how teachers equip the up-and-coming members of the software field
and, if you are already in this profession, I hope that you will take fifteen
minutes to help me achieve this goal.

<span class="gist">Today I am introducing Educational Discussions with Software
  Engineers, or the SEED project, in which I will interview and publish the
  insights from influential members of the software industry.</span> If you are
a software or hardware engineer, quality assurance engineer, database
administrator, software project manager, technology evangelist &mdash; or an
individual who operates in one of the many other important roles in the software
field &mdash; then I hope that you will complete the [SEED survey](/seed/) right
away. I'd love to publish your insights!

You might have noticed that I named this project "SEED" instead of "EDSE", which
would be the most direct acronym to choose. I did this because I want practicing
Software Engineers to have Educational Discussions with the students who enroll
in my courses and students and educators who read my [blog](/blog/). By
partnering with software professionals, I want to "turn around" the educational
process in the same way that I "turned around" the project's name. This will
allow the interviewees to teach both students and educators about the realities
of the software industry. I also hope that the interviewees will plant seeds of
inspiration in all of the individuals who read their published responses.

My role in the SEED project is to administer the [SEED survey](/seed/),
copy-edit and analyze the responses, and then publish them on my [blog](/blog/).
I may also release a retrospective at the start of 2018 in which I will report
back on the key lessons taught by the interviewees and make suggestions for ways
in which educators like me can improve their teaching and research.

{{< include /_gist.qmd >}}

::: {.callout-note appearance="simple"}

## Further Details

Are you an industrialist who wants to make a difference? Please complete the
[SEED survey](/seed/) now! Although I have not published SEED interviews for
several years, I would like publish your insights shortly after you complete the
survey!

:::

{{< include /_back-blog.qmd >}}

