---
author: Gregory M. Kapfhammer
title: Hitchhiker's need free vehicles! A call for open-source statistical analyses in software engineering
date: '2016-01-01'
date-format: YYYY
categories: [post, position statement, software tool]
description: <em>Let's enable the replication of statistical analyses!</em>
aliases: ["/research/software/idea/2016/09/25/2016-Statistical-Software/"]
---

## Introduction

As evident by Arcuri and Briand's paper "A Hitchhiker's guide to statistical
tests for assessing randomized algorithms in software engineering", the field of
search-based software engineering (SBSE) relies on statistical methods to
support the empirical comparison of different techniques. Yet, this statistical
source code is often bespoke and may not be available so that other researchers
can replicate the analyses or learn from the project.

## Vehicles

As a means for improving the maturity of the data analysis methods used in the
SBSE field, I think that it would be useful if there were shared repositories of
well-documented statistical analysis code and replication data. That is, the
SBSE community would advance if its "hitchhikers" had access to "free vehicles"
in the form of GitHub repositories containing the data sets and statistical
analysis code used for published papers.

## Resources

To learn more about the benefits associated with using shared repositories of
statistical code in SBSE, you can read the suggestions in
[@Kapfhammer2016] [{{< iconify fa6-solid book-open >}}](/research/papers/kapfhammer2016/index.qmd)
for improving the study of data arising from experiments with randomized
algorithms. If you would like to examine the source code of that paper, then you
can visit its GitHub repository at <a
  href="https://github.com/gkapfham/sbst2016-paper">gkapfham/sbst2016-paper</a>
Or, do you have ideas about how the SBSE community should create, share, and
apply statistical software? If so, then please <a
  href="/contact/index.qmd">contact</a> me with your thoughts!

::: {.callout-note appearance="simple"}

## Further Details

Interested in learning more about this topic? Since this blog post was written,
my colleagues and students and I have published [@McMinn2016a] [{{< iconify
fa6-solid book-open >}}](/research/papers/mcminn2016a/index.qmd) and released a
replication package for it as well. If you are interested in replicating the
analyses in that paper, then I encourage you to visit <a
  href="https://github.com/gkapfham/vmutation-replicate">gkapfham/vmutation-replicate</a>
on GitHub. You can learn more about the other replication packages that we've
published by checking the [software](/software/index.qmd) page.

:::

{{< include /_back-blog.qmd >}}
