---
title: Software
page-layout: full
---

```{python}
#| echo: false
import re

def count_software() -> int:
    file_path = "../software/index.qmd"
    with open(file_path, "r") as file:
        html_content = file.read()
    pattern = r'<li\s+class="software"\s*>'
    return len(re.findall(pattern, html_content))
```

```{python}
from rich.console import Console
console = Console()
count = count_software()
console.print(
      f":rocket: Here are {count} software projects to which I have contributed!"
)
```

## Research

### Software

<ul>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/AFLuent/AFLuent">afluent</a>: Pytest plugin to support
automated fault localization</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/AVMf/avmf">avmf</a>: Extensible framework for the
search-based alternating variable method</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/flake-it/cannier-framework">cannier-framework</a>:
Flaky test detection with re-running and machine learning</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/kinneerc/ExpOse/">expose</a>: Doubling experiments to
infer actual-worst-case time complexity</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/kanonizo/kanonizo">kanonizo</a>: Effective automated
regression test suite prioritization for JUnit</li>

<li class="software"><a target="_blank" rel="noopener"
href="http://www.mutation-testing.org/">major</a>: Easy and scalable mutation
testing for the Java programming language</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/mccurdyc/mrstudyr">mrstudyr</a>: Retrospectively study
effectiveness of mutation testing techniques</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/PseudoTested/PseudoSweep">pseudosweep</a>:
Find pseudo-tested statements and methods in Java programs</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/flake-it/pytest-cannier">pytest-cannier</a>:
Pytest plugin to characterize Pytest test suites</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/redecheck/redecheck-tool">redecheck</a>: Automated
checking of responsively designed web pages</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/schemaanalyst-team/schemaanalyst">schemaanalyst</a>:
Data generation and mutation analysis for database schemas</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/flake-it/testinspect">testinspect</a>: Pytest plugin to
characterize Pytest test suites</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/flake-it/showflakes">showflakes</a>: Pytest plugin for
automatically finding flaky tests</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/Tada-Project/tada">tada</a>: Automated order-of-growth
analysis for Python functions</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/redecheck/viser">viser</a>: Automated visual
verification of responsive layout failure reports</li>

</ul>

::: {.callout-note appearance="simple"}

#### Research Connection

Many, but not all, of these software tools are connected to the [research
papers](/research/papers/index.qmd) and [research
presentations](/research/presentations/index.qmd) published by me and my
research collaborators. For instance, the papers [@Kinneer2015] [{{< iconify
fa6-solid book-open
>}}](/research/papers/kinneer2015/index.qmd) and
[@Kinneer2015a] [{{< iconify fa6-solid book-open
>}}](/research/papers/kinneer2015a/index.qmd) both describe experiments with
the [expose](https://github.com/kinneerc/ExpOse/) tool. As additional examples,
the [testinspect](https://github.com/flake-it/testinspect) and
[showflakes](https://github.com/flake-it/showflakes) tools both supported
research that resulted in the publication of [@Parry2022a] [{{< iconify
fa6-solid book-open
>}}](/research/papers/parry2022a/index.qmd) and the
[schemaanalyst](https://github.com/schemaanalyst-team/schemaanalyst) tool
enabled the publication of papers like [@Alsharif2020] [{{< iconify fa6-solid
book-open
>}}](/research/papers/alsharif2020/index.qmd). It is also important to note
that, while I played an active role in the conception, documentation, use, and
experimental evaluation of each of these research prototypes, I normally was not
the lead developer of the tool. See the contributor list in each project's
GitHub repository for contributor details!

:::

### Resources

<ul>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/AVMf/avm-bibliography">avm-bibliography</a>: References
on search-based methods</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/curriculum-vitae/">curriculum-vitae</a>: A
curriculum vitae using moderncv and moderntimeline</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/flake-it/flaky-tests-bibliography">flaky-tests-bibliography</a>:
References on flaky test cases</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/philmcminn/new-paper">new-paper</a>: Template for
writing a research paper in LaTeX</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/python-talk-abstracts">python-talk-abstracts</a>:
Details about my Python-related presentations</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/research-bibliography">research-bibliography</a>:
References for all of my research deliverables</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/schemaanalyst/schemaanalyst-bibliography">schemaanalyst-bibliography</a>:
References on testing database applications</li>

</ul>

::: {.callout-note appearance="simple"}

#### Research Connection

Interested in conducting research that builds or cites on the [research
papers](/research/papers/index.qmd) and [research
presentations](/research/presentations/index.qmd) published by me and my
research collaborators? You can check out these resources for abstracts of
conference talks, BiBTeX references to papers, and templates for writing a
research paper or a curriculum vitae. For instance, the [avm-bibliography]()
documents the research articles cited in the [@McMinn2016b] [{{< iconify
fa6-solid book-open
>}}](/research/papers/mcminn2016b/index.qmd) paper that describes the
[avmf](https://github.com/AVMf/avmf) tool.

:::

### Papers

<ul>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/AVMf/avmframework-paper">avmframework-paper</a>: Source
code for a research paper at SSBSE 2016</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/ast2016-paper">ast2016-paper</a>: Source code
for a research paper at AST 2016</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/schemaanalyst/icsme2016-mrstudyrtool-paper">icsme2016-mrstudyrtool-paper</a>:
Source code for a tool paper at ICSME 2016</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/schemaanalyst/icsme2016-satool-paper">icsme2016-satool-paper</a>:
Source code for a tool paper at ICSME 2016</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/sbst2016-paper">sbst2016-paper</a>: Source
code for a research paper at SBST 2016</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/seke2015-paper">seke2015-paper</a>: Source
code for a research paper at SEKE 2015</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/seke2015-tool-paper">seke2015-tool-paper</a>:
Source code for a tool paper at SEKE 2015</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/per2012-paper">per2012-paper</a>: Source code
for a research paper in the PER journal</li>

</ul>

::: {.callout-note appearance="simple"}

#### Research Connection

While I don't release the LaTeX source code of most of the [research
papers](/research/papers/index.qmd) that my research collaborators and I
publish, I've made the GitHub repository of select papers publicly available.
For instance, the source code that results in the paper [@McMinn2016a] [{{<
iconify fa6-solid book-open
>}}](/research/papers/mcminn2016a/index.qmd) is in the
[gkapfham/ast2016-paper](https://github.com/gkapfham/ast2016-paper) GitHub
repository. Check it out to see how we structure papers!

:::

### Presentations

<ul>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/GatorEducator/PyCon2025-EducationAndTypingSummit-Presentations">pycon2025-educationsummit-presentations</a>:
Presentation slides the PyCon 2025 talks</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/pyohio2021-presentation">pyohio2021-presentation</a>:
Presentation slides the PyOhio 2021 talk</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/pycon2019-functionfiasco-poster">pycon2019-functionfiasco-poster</a>:
Presentation slides for a PyCon 2019 talk</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/pycon2019-gatorgrouper-poster">pycon2019-gatorgrouper-poster</a>:
Poster for PyCon 2019 session</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/pyohio2019-presentation">pyohio2019-presentation</a>:
Presentation slides for a PyOhio 2019 talk</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/pygotham2018-presentation">pygotham2018-presentation</a>:
Presentation slides for a PyGotham 2018 talk</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/pyohio2018-presentation">pyohio2018-presentation</a>:
Presentation slides for a PyOhio 2018 talk</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/mccurdyc/icsme2016-presentation">icsme2016-presentation</a>:
Presentation slides for an ICSME 2016 talk</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/schemaanalyst/icsme2016-tool-presentation">icsme2016-tool-presentation</a>:
Presentation slides for an ICSME 2016 talk</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/AVMf/ssbse2016-presentation">ssbse2016-presentation</a>:
Presentation slides an SSBSE 2016 talk</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/sbst2016-presentation">sbst2016-presentation</a>:
Presentation slides an SBST 2016 talk</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/allegheny2015-presentation">allegheny2015-presentation</a>:
Presentation slides an Allegheny College talk</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/seke2015-panel-presentation">seke2015-panel-presentation</a>:
Presentation slides a SEKE 2015 panel talk</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/seke2015-presentation">seke2015-presentation</a>:
Presentation slides a SEKE 2015 talk</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/qsic2014-presentation">qsic2014-presentation</a>:
Presentation slides a QSIC 2014 talk</li>

</ul>

::: {.callout-note appearance="simple"}

#### Research Connection

Did you know that I use LaTeX, JavaScript, Markdown, and other programming
languages to create many of  [research
presentations](/research/presentations/index.qmd)? By studying the source code
for presentations like [@Kapfhammer2021] [{{< iconify fa6-solid book-open
>}}](/research/presentations/kapfhammer2021/index.qmd) and
[@Kapfhammer2021a] [{{< iconify fa6-solid book-open
>}}](/research/presentations/kapfhammer2021a/index.qmd) you can see how we
create and layout the graphical content! My colleagues and I have also release
the source code for the presentations that accompany select research papers,
like [@McCurdy2016] [{{< iconify fa6-solid book-open
>}}](/research/papers/mccurdy2016/index.qmd).

:::

### Replication

<ul>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/flake-it/cannier-experiment">cannier-experiment</a>:
Data and analysis code for an ESE 2023 paper</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/schemaanalyst/domino-replicate">domino-replicate</a>:
Data and analysis code for an ICST 2018 paper</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/flake-it/flake16-framework">flake16-framework</a>:
Data, analysis, and tooling for an ICST 2022 paper</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/flake-it/flaky-test-survey-replication-package">flaky-test-survey-replication-package</a>:
Code for an ICSE-SEIP 2022 paper</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/schemaanalyst/imdetect-replicate">imdetect-replicate</a>:
Data and analysis code for a TSE 2019 paper</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/redecheck/jstvr-webpages">jstvr-webpages</a>:
Experimental subjects for a JSTVR 2020 paper</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/flake-it/showflakes-framework">showflakes-framework</a>:
Data and analysis code for an AST 2022 paper</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/schemaanalyst/sticcer-replicate">sticcer-replicate</a>:
Data and analysis code for an ICST 2020 paper</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/vmutation-replicate">vmutation-replicate</a>:
Data and analysis code for an AST 2016 paper</li>

</ul>

::: {.callout-note appearance="simple"}

#### Research Connection

Whenever possible, my collaborators and I publish replication packages to
support our [research papers](/research/papers/index.qmd) and [research
presentations](/research/presentations/index.qmd). For instance, you can review
all of the survey data from [@Parry2022b] [{{< iconify fa6-solid book-open
>}}](/research/papers/parry2022b/index.qmd) and try out the tooling used to
run the experiments that we report on in [@Alsharif2020] [{{< iconify fa6-solid
book-open
>}}](/research/papers/alsharif2020/index.qmd). Check the above GitHub
repositories for more details!

:::

## Teaching

### Software

<ul>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/GatorEducator/cellveyor">cellveyor</a>: Easily convey
reports from Google Sheets to GitHub</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/AstuteSource/chasten">chasten</a>: Configurable
linting tool that uses XPath expressions</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/GatorEducator/dockagator">dockagator</a>: Docker
container and infrastructure for GatorGrader</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/GatorEducator/execexam">execexam</a>: Run
executable examinations to assess programming skills</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/GatorEducator/gatorgrade">gatorgrade</a>: Python
front-end for the GatorGrader assessment tool</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/GatorEducator/gatorgrader">gatorgrader</a>: Automated
assessment for source code and writing</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/GatorEducator/gatorgradle">gatorgradle</a>: Gradle
plugin for efficient use of GatorGrader</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/GatorEducator/gatorgrouper">gatorgrouper</a>: Group
formation tool for team-based courses</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/GatorEducator/reporover">reporover</a>: Easily manage
components in GitHub repositories</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/GatorEducator/SheetShuttle">sheetshuttle</a>: Tool for
data transfer between Google Sheets and GitHub</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/seed">seed</a>: Analyzer and displayer of
responses to the SEED survey</li>

</ul>

::: {.callout-note appearance="simple"}

#### Teaching Connection

My students, colleagues, and I create and maintain several tools that support
the automated assessment of the source code and technical writing that students
complete as part of a course project. You can learn more about the tools that we
have implemented and deployed by checking out presentations like
[@Kapfhammer2018] [{{< iconify fa6-solid book-open
>}}](/research/presentations/kapfhammer2018/index.qmd) and
[@Kapfhammer2019] [{{< iconify fa6-solid book-open
>}}](/research/presentations/kapfhammer2019/index.qmd).
Check out the above GitHub repositories for details about how to use
these tools in your teaching!

:::

### Platforms

<ul>

<li class="software"><a target="_blank" rel="noopener"
href="https://www.algorithmology.org">Algorithm Analysis</a>: Implement and evaluate
correct and efficient algorithms
</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://proactiveprogrammers.com/data-abstraction/introduction-data-abstraction/">Data
Abstraction</a>: Build and manipulate correct and efficient data structures
</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://proactiveprogrammers.com/data-abstraction/introduction-discrete-structures/">
Discrete Structures</a>: Clearly connect mathematics to Python programming
</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://www.developerdevelopment.com/">
Developer Development</a>: Team-based introduction to building software systems
</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://www.os-sketch.com/">
Operating Systems</a>: Build and understand operating system components
</li>

</ul>

::: {.callout-note appearance="simple"}

#### Teaching Connection

Please visit the web site for each of my course platforms to learn more about
the specific technologies that we use to deploy each site that I use for
[teaching](/teaching/index.qmd).

:::

### Courses

<ul>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/Allegheny-Computer-Science-102-F2020/cs102-F2020-plans">cs102F2020</a>:
Course content for Computer Science 102 Fall 2020</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/Allegheny-Computer-Science-302-F2020/cs302-F2020-plans">cs302F2020</a>:
Course content for Computer Science 302 Fall 2020</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/Allegheny-Computer-Science-100-S2020/">cs100S2020</a>:
Course content for Computer Science 100 Spring 2020</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/Allegheny-Computer-Science-203-S2020/">cs203S2020</a>:
Course content for Computer Science 203 Spring 2020</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/Allegheny-Computer-Science-100-F2019">cs100F2019</a>:
Course content for Computer Science 100 Fall 2019</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/Allegheny-Computer-Science-101-F2019">cs101F2019</a>:
Course content for Computer Science 101 Fall 2019</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/Allegheny-Computer-Science-203-S2019">cs203S2019</a>:
Course content for Computer Science 203 Spring 2019</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/Allegheny-Computer-Science-302-S2019">cs302S2019</a>:
Course content for Computer Science 302 Spring 2019</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/Allegheny-Computer-Science-481-S2019">cs481S2019</a>:
Course content for Computer Science 481 Spring 2019</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/Allegheny-Computer-Science-100-F2018">cs100F2018</a>:
Course content for Computer Science 100 Fall 2018</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/Allegheny-Computer-Science-101-F2018">cs101F2018</a>:
Course content for Computer Science 101 Fall 2018</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/Allegheny-Computer-Science-103-S2018">cs103S2018</a>:
Course content for Computer Science 103 Spring 2018</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/Allegheny-Computer-Science-112-S2018">cs112S2018</a>:
Course content for Computer Science 112 Spring 2018</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/Allegheny-Computer-Science-111-F2017">cs111F2017</a>:
Course content for Computer Science 111 Fall 2017</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/Allegheny-Computer-Science-280-F2017">cs280F2017</a>:
Course content for Computer Science 280 Fall 2017</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/Allegheny-Computer-Science-600-F2017">cs600F2017</a>:
Course content for Computer Science 600 Fall 2017</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/cs111S2017">cs111S2017</a>: Course content for
Computer Science 111 Spring 2017</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/fs102S2017">fs102S2017</a>: Course content for
First-Year/Sophomore 102 Spring 2017</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/cs111F2016">cs111F2016</a>: Course content for
Computer Science 111 Fall 2016</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/cs112F2016">cs112F2016</a>: Course content for
Computer Science 112 Fall 2016</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/cs111S2016">cs111S2016</a>: Course content for
Computer Science 111 Spring 2016</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/cs441S2016">cs441S2016</a>: Course content for
Computer Science 441 Spring 2016</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/cs111F2015">cs111F2015</a>: Course content for
Computer Science 111 Fall 2015</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/cs280F2015">cs280F2015</a>: Course content for
Computer Science 280 Fall 2015</li>

</ul>

::: {.callout-note appearance="simple"}

#### Teaching Connection

Prior to developing course platforms for each of the classes that I teach, I
created GitHub repositories and/or organizations for every course and linked to
them from my professional web site's [teaching](/teaching/index.qmd) page. While
I no longer maintain out-of-date course content and instead encourage learners
to visit my course platforms, you may [contact me](/contact/) with your request
for old materials.

:::

## Open-Source

### Configurations

<ul>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/dotfiles">dotfiles</a>: Configuration files
for my development environment</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/nixos">nixos</a>: Configuration files
for the NixOS Linux distribution</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/tmuxinators">tmuxinators</a>: Configuration
files for the terminal multiplexer</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/vim-vitamin-onec">vim-vitamin-onec</a>: Dark
color scheme for Vim and Neovim</li>

</ul>

::: {.callout-note appearance="simple"}

#### Software Connection

I aim to have a well-documented software tools that I run on the laptop
that I use for all my professional activities. I hope that some of these
configurations can help you to setup your own workstation for teaching,
research, and software engineering. Checkout
my configuration of [NixOS](https://nixos.org/)!

:::

### Defects and Discussions

<ul>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/artur-shaik/vim-javacomplete2/issues/277">artur-shaik/vim-javacomplete2
Issue #277</a>: Errors when starting Vim ...</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/asdf-vm/asdf-nodejs/issues/277">asdf-vm/asdf-nodejs
Issue #277</a>: bug: Cannot create directory ...</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/education/classroom/issues/1117">education/classroom
#1117</a>: Internal Server Error 500 When Accessing ...</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/education/classroom/issues/1543">education/classroom
#1543</a>: Students suddenly cannot import repo ...</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/git-lfs/git-lfs/issues/3474">git-lfs/git-lfs #3474</a>:
Installation in Ubuntu is not working</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/junegunn/fzf/issues/712">junegunn/fzf Issue #712</a>:
Setting foreground without background</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/kshenoy/vim-signature/issues/164">kshenoy/vim-signature
Issue #164</a>: Special characters for markers?</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/lervag/vimtex/issues/176">lervag/vimtex Issue #176</a>:
Latexmk crashes when loading second LaTeX file</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/lervag/vimtex/issues/177">lervag/vimtex Issue #177</a>:
Many Zathura windows in a multi-file project</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/lervag/vimtex/issues/178">lervag/vimtex Issue #178</a>:
Second MuPDF window in a multi-file project</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/lervag/vimtex/issues/181">lervag/vimtex Issue #181</a>:
Forward search not working with old Zathura</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/lervag/vimtex/issues/312">lervag/vimtex Issue #312</a>:
Additional MuPDF window on forward search</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/lervag/vimtex/issues/762">lervag/vimtex Issue #762</a>:
BibTeX reference completion crashes with ...</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/lervag/vimtex/issues/903">lervag/vimtex Issue #903</a>:
Restarting continuous compilation breaks PDF ...</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/ludovicchabant/vim-gutentags/issues/168">ludovicchabant/vim-gutentags
Issue #168</a>: Error when deoplete installed</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/ludovicchabant/vim-gutentags/issues/178">ludovicchabant/vim-gutentags
Issue #178</a>: Halt on exit</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/ncm2/ncm2-jedi/issues/9">ncm2/ncm2-jedi Issue #9</a>:
AttributeError: module 'jedi' has no attribute 'Script'</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/neovim/neovim/issues/6204">neovim/neovim Issue
#6204</a>: Using FZF turns off relativenumber</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/ms-jpq/coq_nvim/issues/265">ms-jpq/coq_nvim Issue
#264</a>: Neovim 0.5.0 Crashes with segmentation fault ...</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/neovim/neovim/issues/8775">neovim/neovim Issue
#8775</a>: Version 0.3.2 interface deranged</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/pypa/pipenv/issues/3247">pypa/pipenv Issue #3247</a>:
pipenv --three fails</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/quarto-dev/quarto-cli/discussions/5900">quarto-dev/quarto-cli Discussion #5900</a>:
Is is possible to avoid the flash ...</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/spookylukey/pyastgrep/discussions/18">spookylukey/pyastgrep Discussion #18</a>:
Using pyastgrep as a library</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/Shougo/deoplete.nvim/issues/500">Shougo/deoplete.nvim
#500</a>: nvim source deoplete/util.vim slow</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/Shougo/deoplete.nvim/issues/508">Shougo/deoplete.nvim
#508</a>: Deoplete.nvim does not provide completions ...</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/wellle/tmux-complete.vim/issues/63">welle/tmux-complete.vim
Issue #63</a>: Tmux completion no longer works</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/vim-airline/vim-airline/issues/1631">vim-airline/vim-airline
#1631</a>: Missing spaces in tabline</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/w0rp/ale/issues/182">w0rp/ale Issue #182</a>: R
support</li>

</ul>

::: {.callout-note appearance="simple"}

#### Software Connection

Whenever possible, I participate in the maintenance and enhancement of
open-software software tools by reporting defects and participating in
discussions. Along with documenting my software adventures, I aim for these
notes to help and encourage the maintainers of open-source software.

:::

### Prior Work

<ul>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/gelations/">gelations</a>: Test suite
prioritization with order-based genetic algorithms</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/kauffmj/modificare/">modificare</a>: Reproducible
experimentation with regression testing techniques</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/kauffmj/proteja/">proteja</a>: Easy-to-use techniques
for test suite reduction and prioritization</li>

<li class="software"><a target="_blank" rel="noopener"
href="https://github.com/gkapfham/raise/">raise</a>: Comprehensive test suite
execution and management</li>

</ul>

::: {.callout-note appearance="simple"}

#### Software Connection

Although I no longer maintain any of these software tools, I'm glad to make them
available as a history of prior work and as a source of inspiration and ideas
for software engineers. 

:::
