---
author: Gregory M. Kapfhammer
title: Quick tips for technical writing with LaTeX and Neovim
date: '2017-01-01'
date-format: YYYY
categories: [post, software tool, technical writing]
description: <em>You can tweak Neovim for technical writing!</em>
aliases: ["/writing/tool/vim/2017/06/26/Neovim-Remote-Latex/"]
---

I enjoy using Vim when I am writing LaTeX documents for my
[teaching]({{site.baseurl}}teaching/) and [research]({{site.baseurl}}research/).
Since [Neovim](https://neovim.io/) became available I have been using it as a
&mdash; capable and compelling &mdash; alternative to Vim. I find that Neovim
works really well and that its plugin ecosystem is great! But, if you want the
[vimtex](https://github.com/lervag/vimtex) plugin to work with Neovim, then you
need to take two extra steps, as explained in this post.

What do you need to do to write LaTeX in Neovim? Well, when I was writing
[@Walsh2017a] [{{< iconify fa6-solid book-open >}}](/research/papers/walsh2017a/index.qmd) with Neovim,
I needed to change my `.vimrc` file and install a plugin. After following the
instructions to install the <a
  href="https://github.com/mhinz/neovim-remote">neovim-remote</a> plugin, I
added this code segment to ensure that `vimtex` can communicate with the
`latexmk` process that is compiling my paper.

```vim
if has("nvim")
  let g:vimtex_latexmk_progname = 'nvr'
endif
```

Wait! There is one more thing. If you, like me, have been using Vim for many
years and only recently started to use Neovim, then you will also need to run
commands like the following so that you can "retrofit" your Vim configuration to
work correctly with Neovim. Or, you can re-write your Vim configuration in Lua!

```vim
ln -s ~/.vim ~/.nvim
ln -s ~/.vimrc ~/.nvim/init.vim
```

{{< include /_gist.qmd >}}

::: {.callout-note appearance="simple"}

## Stay Connected

Are you interested in learning more about how I configure Vim and Neovim? Please
study the source code of my `.vimrc` that is available in the GitHub repository
[gkapfham/dotfiles](https://github.com/gkapfham/dotfiles). With that said, since
this post was written I've converted my Neovim configuration to use Lua and the
[lazy.nvim](https://github.com/folke/lazy.nvim) plugin manager. This means that
you should aim to study my `init.lua` file instead!

:::

{{< include /_back-blog.qmd >}}
