"""Generate a minimal Bootstrap Icons CSS subset with only the icons actually used."""

import argparse
import os
import shutil
import subprocess
from pathlib import Path

from rich.console import Console

console = Console()

# base directory
BASE_DIR = Path(__file__).parent.parent
SITE_LIBS = BASE_DIR / "_site/site_libs/bootstrap"
ORIGINAL_CSS = SITE_LIBS / "bootstrap-icons.css"
SUBSET_CSS = SITE_LIBS / "bootstrap-icons.subset.css"
BACKUP_CSS = SITE_LIBS / "bootstrap-icons.css.backup"

# icon unicode mappings (Bootstrap Icons 1.11.1)
ICON_CODES = {
    "github": "\\f3ed",
    "google": "\\f3f0",
    "linkedin": "\\f472",
    "mastodon": "\\f647",
    "megaphone": "\\f484",
    "search": "\\f52a",
    "sort-down": "\\f575",
    "x-lg": "\\f659",
}


def find_all_icons():
    """Scan all HTML files and find Bootstrap Icons used.

    returns a sorted list of icon names.
    """
    icons = set()
    # find bi-* classes in HTML files
    result = subprocess.run(
        [
            "grep",
            "-roh",
            r'class="[^"]*bi-[a-z-]*[^"]*"',
            str(BASE_DIR / "_site"),
            "--include=*.html",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    for match in result.stdout.strip().split("\n"):
        if match:
            # extract icon names from class="bi bi-github"
            classes = match.replace('class="', "").replace('"', "").split()
            for cls in classes:
                if cls.startswith("bi-"):
                    icon_name = cls.replace("bi-", "")
                    icons.add(icon_name)
    # also check source files for icon declarations in _quarto.yml
    result = subprocess.run(
        ["grep", "-rh", r"icon:", str(BASE_DIR), "--include=*.yml"],
        capture_output=True,
        text=True,
        check=False,
    )
    for line in result.stdout.strip().split("\n"):
        if line and "icon:" in line:
            # extract icon name: "    icon: github" or "icon: megaphone"
            icon_name = line.split("icon:")[-1].strip()
            if icon_name and not icon_name.startswith('"'):
                icons.add(icon_name)
    return sorted(icons)


def generate_css(icons):
    """Generate minimal Bootstrap Icons CSS with only specified icons.

    args:
        icons: list of icon names to include
    """
    css = """/*!
 * Bootstrap Icons v1.11.1 (https://icons.getbootstrap.com/)
 * Minimal subset - only icons actually used
 * Auto-generated by scripts/generate-bootstrap-icons-subset.py
 */

@font-face {
  font-display: block;
  font-family: "bootstrap-icons";
  src: 
url("./bootstrap-icons.woff?2820a3852bdb9a5832199cc61cec4e65") format("woff");
}

.bi::before,
[class^="bi-"]::before,
[class*=" bi-"]::before {
  display: inline-block;
  font-family: bootstrap-icons !important;
  font-style: normal;
  font-weight: normal !important;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  vertical-align: -.125em;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

/* icon definitions */
"""
    # add icon definitions
    for icon in icons:
        if icon in ICON_CODES:
            css += f'.bi-{icon}::before {{ content: "{ICON_CODES[icon]}"; }}\n'
    return css


def main():
    """Generate the Bootstrap Icons subset CSS file."""
    # parse command-line arguments
    parser = argparse.ArgumentParser(
        description="Generate minimal Bootstrap Icons CSS with only used icons"
    )
    parser.add_argument(
        "--replace",
        action="store_true",
        help="Replace bootstrap-icons.css with the subset (use in CI only)",
    )
    args = parser.parse_args()
    # check if _site directory exists
    if not SITE_LIBS.exists():
        console.print(":cross_mark: _site/site_libs/bootstrap/ directory not found!")
        console.print(":information: Run 'quarto render' first to generate the site.")
        return
    # check if original CSS exists
    if not ORIGINAL_CSS.exists():
        console.print(f":cross_mark: {ORIGINAL_CSS.name} not found in {SITE_LIBS}!")
        console.print(":information: Run 'quarto render' first to generate the site.")
        return
    console.print(":magnifying_glass_tilted_left: Scanning for Bootstrap Icons...")
    icons = find_all_icons()
    if not icons:
        console.print(":cross_mark: No icons found!")
        return
    console.print(f":check_mark_button: Found {len(icons)} unique icons:")
    for icon in icons:
        console.print(f"   - {icon}")
    # generate minimal CSS
    console.print("\n:pencil: Generating minimal CSS...")
    css = generate_css(icons)
    # write to subset file first
    SUBSET_CSS.write_text(css)
    console.print(f":floppy_disk: Wrote subset to: {SUBSET_CSS.name}")
    # show size comparison
    if ORIGINAL_CSS.exists():
        original_size = ORIGINAL_CSS.stat().st_size
        subset_size = SUBSET_CSS.stat().st_size
        reduction = ((original_size - subset_size) / original_size) * 100
        console.print("\n:bar_chart: Size comparison:")
        console.print(f"   Original: {original_size:,} bytes ({ORIGINAL_CSS.name})")
        console.print(f"   Subset:   {subset_size:,} bytes ({SUBSET_CSS.name})")
        console.print(f"   Reduction: {reduction:.1f}%")
    # optionally replace the original file (CI only)
    if args.replace:
        console.print(
            f"\n:warning: Replacing {ORIGINAL_CSS.name} with subset (--replace flag)"
        )
        # create backup if it doesn't exist
        if not BACKUP_CSS.exists():
            console.print(f":package: Creating backup: {BACKUP_CSS.name}")
            shutil.copy2(ORIGINAL_CSS, BACKUP_CSS)
        # replace original with subset
        # set file permissions to writable first (Quarto sets files as read-only)
        os.chmod(ORIGINAL_CSS, 0o600)
        shutil.copy2(SUBSET_CSS, ORIGINAL_CSS)
        console.print(":check_mark: Replaced successfully!")
    else:
        console.print(
            f"\n:information: Testing mode - {ORIGINAL_CSS.name} was not modified"
        )
        console.print(
            f":information: Use --replace flag to replace {ORIGINAL_CSS.name} with subset"
        )
    console.print("\n:party_popper: Done!")


if __name__ == "__main__":
    main()
