---
title: Biography
page-layout: full
echo: true
jupyter: python3
listing:
  - id: featured-service-biography
    contents:
      - "../service/**/*.qmd"
      - "!../service/index.qmd"
      - ../service/service.yml
    sort:
      - "date desc"
      - "year-range desc"
      - "title"
    type: table
    categories: false
    date-format: "YYYY"
    sort-ui: false
    filter-ui: false
    fields: [title, year-range, description, service-count]
    field-display-names:
      description: "Role(s)"
      title: "Venue"
      year-range: "Year(s)"
      service-count: "Count"
    field-links: []
    max-items: 10
    page-size: 10
  - id: featured-media-biography
    contents:
      - ../media/media.yml
    sort:
      - "date desc"
      - "title"
    type: table
    categories: false
    date-format: medium
    sort-ui: false
    filter-ui: false
    fields: [date, description, title, venue]
    field-display-names:
      title: "Event"
      venue: "Venue"
      description: "Role"
    field-links: []
    max-items: 15
    page-size: 15
---

```{python}
from rich.console import Console
console = Console()
console.print(
    ":rocket: Hi! I'm a researcher, teacher, software developer, and podcaster!"
)
```

## Overview

Guided by my <a href = "/principles/">professional principles</a>, I am an
Associate Professor in the <a href="http://www.cs.allegheny.edu">Department of
  Computer Science</a> at <a href="http://www.allegheny.edu">Allegheny
  College</a>. I earned a PhD from the <a href="https://cs.pitt.edu">Department
  of Computer Science</a> at the <a href="http://www.pitt.edu">University of
  Pittsburgh</a>, writing a PhD dissertation on database application testing
that was supervised by <a href="http://www.cs.virginia.edu/~soffa/">Mary Lou
  Soffa</a> and published as [@Kapfhammer2007d] [{{< iconify fa6-solid
book-open
>}}](/research/papers/kapfhammer2007d/index.qmd).
I also earned a BSc in Computer Science from Allegheny College and an MSc in
Computer Science from the University of Pittsburgh. Previously I was a
short-term visitor in the <a href="http://www.cs.virginia.edu">Department of
  Computer Science</a> at the <a href="http://www.virginia.edu">University of
  Virginia</a>, the Institute of Applied Information Processing at the <a
  href="http://www.uni-ulm.de/en">University of Ulm</a>, and the <a
  href="https://www.sheffield.ac.uk/dcs">Department of Computer Science</a> at
the <a href="http://www.sheffield.ac.uk/">University of Sheffield</a>. In a
prior position, I was a research associate at Cigital, a software company
acquired by <a href="https://www.synopsys.com/">Synopsys</a>. My work is
partially funded by <a href =
  "https://research.fb.com/blog/2019/10/announcing-the-winners-of-the-2019-testing-and-verification-research-awards/">Facebook
  Research</a> and the <a href =
  "https://foundation.mozilla.org/en/what-we-fund/awards/responsible-computer-science-challenge/winners/">Mozilla
  Foundation</a>.

## Teaching

As an educator, I teach [courses](/teaching/index.qmd) in the alphabetically
ordered areas of algorithm analysis, discrete structures, data management,
distributed systems, software engineering, software testing, operating systems,
and web development.</span> I am also a research adviser for undergraduate and
graduate theses and PhD dissertations. My expertise in teaching was recognized
when Allegheny College presented me with the [Thoburn Award for Excellence in
Teaching](https://sites.allegheny.edu/alumni/award-recipients/#thoburn). As a
leader of software engineering teams, I create useful educational
[software](/software/index.qmd) that supports automated tasks such as project
assessment and team formation.

## Research

Funded by [Facebook
Research](https://research.fb.com/blog/2019/10/announcing-the-winners-of-the-2019-testing-and-verification-research-awards/)
and the [Mozilla
Foundation](https://foundation.mozilla.org/en/what-we-fund/awards/responsible-computer-science-challenge/winners/),
I conduct [research](/research/index.qmd) in areas such as software engineering
and software testing. Collaborating with a diverse and skilled group of students
and colleagues, I complete research that results in award-winning and frequently
cited research [papers](/research/papers/index.qmd), oft-complimented
[presentations](/research/presentations/index.qmd), useful free and open-source
[software](/software/index/qmd), and valued [service](/service/index.qmd) to a
variety of organizations. I am an associate editor for the [Journal of Software:
Evolution and Process](https://onlinelibrary.wiley.com/journal/20477481), an
academic editor for the [PeerJ Computer
Science](https://peerj.com/computer-science/) journal, a program committee
member for conferences like the [International Conference on Software Testing,
Verification and Validation](https://cs.gmu.edu/icst/index.html), and a reviewer
for journals such as [Transactions on Software
Engineering](https://www.computer.org/csdl/journal/ts). Along with serving as a
review panelist at the [U.S. National Science Foundation](https://nsf.gov/), I
lead as a session chair, program chair, and general chair for international
workshops and conferences. As a member of software engineering teams, I create
useful research [software](/software/index.qmd) for the purposes of
experimentation, replication, and technology transfer.

My co-authors and I publish papers like [@Walsh2017] [{{< iconify
fa6-solid book-open
>}}](/research/papers/walsh2017/index.qmd), [@Alsharif2018] [{{< iconify fa6-solid book-open >}}](/research/papers/alsharif2018/index.qmd), and
[@McMinn2019] [{{< iconify fa6-solid book-open >}}](/research/papers/mcminn2019/index.qmd) at venues like the <a href =
  "https://conf.researchr.org/series/issta">International Symposium on Software
  Testing and Analysis</a>, the <a href =
  "https://cs.gmu.edu/icst/index.html">International Conference on Software
  Testing, Verification and Validation</a>, and <a href =
  "https://www.computer.org/csdl/journal/ts">Transactions on Software
  Engineering</a>.
Several of these papers were recognized with awards.
For instance, the paper [@Kapfhammer2003] [{{< iconify fa6-solid book-open >}}](/research/papers/kapfhammer2003/index.qmd)
received the ACM
SIGSOFT Distinguished Paper Award at the <a
  href="http://esecfse.cs.helsinki.fi/">ACM SIGSOFT Foundations of Software
  Engineering Conference (ESEC/FSE 2003)</a>.
The paper [@Conrad2010a] [{{< iconify fa6-solid book-open >}}](/research/papers/conrad2010a/index.qmd) was
the best paper in the <a
  href="http://www.sigevo.org/gecco-2010/organizers-tracks.html#sbse">Search-Based
  Software Engineering Track</a> of the <a
  href="http://www.sigevo.org/gecco-2010/">ACM SIGEVO Genetic and Evolutionary
  Computation Conference (GECCO 2010)</a>.
My presentation for
the paper [@Kapfhammer2016] [{{< iconify fa6-solid book-open >}}](/research/papers/kapfhammer2016/index.qmd)
won the
best presentation award at the <a href="https://cse.sc.edu/~ggay/sbst2016/">9th
  International Workshop on Search-Based Software Testing (SBST 2016)</a>.
The paper [@Althomali2019] [{{< iconify fa6-solid book-open >}}](/research/papers/althomali2019/index.qmd)
at the <a href =
  "http://icst2019.xjtu.edu.cn/index.htm">12th International International
  Conference on Software Testing, Verification and Validation (ICST 2019)</a>,
won the distinguished paper award from the <a href =
  "http://www.cs-tcse.org/">IEEE Technical Council on Software Engineering</a>.

## Expertise

### Research Service

I recently leveraged my scientific expertise to serve the following venues:

:::{#featured-service-biography}
:::

### Media Engagements

My technical expertise led to these recent media engagements:

:::{#featured-media-biography}
:::

::: {.callout-note appearance="simple"}

## Enthusiastic Invitation

Do you work in one of my areas of expertise? Are you interested in
collaborating with me on a research, software engineering, or educational
project? Do you think that your knowledge and skills equip you to be guest on
the [Software Engineering Radio](https://www.se-radio.net/) podcast that I
co-host? Or, would you like me to be a guest on a podcast that you host? If you
answered "yes" to one or more of these questions, then I invite you to
[contact](/contact/index.qmd) me to share your ideas!

:::
