---
author: Gregory M. Kapfhammer
title: SEED Interview with Suvarshi Bhadra
date: '2019-01-01'
date-format: YYYY
categories: [post, industry connections, seed interview]
description: <em>Let's learn from Suvarshi Bhadra!</em>
aliases: ["/seed/interview/software/2017/11/27/SEED-Suvarshi-Bhadra/"]
interviewee: Suvarshi Bhadra
company_name: "Facebook"
title_name: "Software Engineer"
web_site: "https://www.linkedin.com/in/sbhadra/"
---

## SEED Interview

As part of the [SEED project](/blog/introducing-seed-survey/index.qmd), I
recently talked with [{{< meta interviewee >}}]({{< meta web_site >}}), a {{<
meta title_name >}} at {{< meta company_name >}}. In this interview, Suvarshi
told me that software engineers must commit to continuous learning throughout
their careers. He also said that students who want to be software engineers
should focus on following a software idea from its inception to its completion
and release. Read Suvarshi's responses to the three SEED questions to learn more
about his unique perspective on the engineering of software in industry.

### What is one fun fact that you can share about your company or a current project?

Engineers joining Facebook don't have a position or role set aside for them.
This was very confusing to me at first. "Don't they know what they want me to
work on?" I wondered. Instead, after a 6-week bootcamp, I was told to pick any
team that I wanted from up to 50+ teams across the company! The thinking goes
that when engineers are working on problems that they want to solve the company
is more impactful.

### What is the greatest challenge that you face when working in your field?

In this field, the learning never stops. There is always more to learn, more to
do, and the pace of development can always be improved. So maintaining a balance
between work, personal hobbies, and family time is the greatest challenge in
this field.

### What is one point of advice that you can give to people who plan to enter your field?

Build an application from end to end &mdash; whether it be a website, mobile
app, or a game. This will give you a high-level understanding of how all the
pieces fit together. Understanding the big picture can keep you motivated as you
dive into the details of networking, databases, or whatever else you want to
learn.

::: {.callout-note appearance="simple"}

## Further Details

Do you have any questions about this interview? Or, do you have a response to
Suvarshi's ideas? If you do, then I hope that you will [contact](/contact/) me
to share some of your thoughts. Or, do you want to be updated when I publish new
interviews in this series? If you do, then please [subscribe](/support/) to my
mailing list.

:::

{{< include /_back-blog.qmd >}}
