---
author: Gregory M. Kapfhammer
title: SEED Interview with Kara King
date: '2018-01-01'
date-format: YYYY
categories: [post, industry connections, seed interview]
description: <em>Let's learn from Kara King!</em>
aliases: ["/seed/interview/software/2017/10/23/SEED-Kara-King/"]
interviewee: Kara King
title_name: "SAP developer"
web_site: "https://www.linkedin.com/in/kara-king-b245a259"
---

## SEED Interview

As part of the [SEED project](/blog/introducing-seed-survey/index.qmd), I
recently talked with [{{< meta interviewee >}}]({{< meta web_site >}}), a {{<
meta title_name >}} at {{< meta company_name >}}. In this interview, Timothy
shared with me that an engineer in industry must be able to develop new ideas
and discern the bigger picture of a technical project. Timothy also explained
that technology companies must pivot to best engage with new markets and
opportunities. Read Timothy's responses to the three SEED questions to learn
more about his unique perspective on the engineering of software.

### What is one fun fact that you can share about your company or a current project?

FirstEnergy has a wide range of jobs, with the information technology (IT)
division focusing on the use of three different programming languages. So,
there are always areas in which you can learn and grow at FirstEnergy! I use
ABAP or the Advanced Business Application Programming language. ABAP is the
language for SAP and is written in German &mdash; so if you know German, ABAP
may be the development language for you!

### What is the greatest challenge that you face when working in your field?

The greatest challenge I face as a developer at FirstEnergy is communicating
with business stakeholders. As a developer you must take business requirements
and turn them into code &mdash; however, many times the business clients do not
even know themselves what they want in their desired product!

### What is one point of advice that you can give to people who plan to enter your field?

Networking is a huge advantage when searching for a job. I still network in my
current job in case I have a desire to "test the waters" in a different part of
my company. Also, take advantage of internships &mdash; they get your foot in
the door!

::: {.callout-note appearance="simple"}

## Further Details

Do you have any questions about this interview? Or, do you have a response to
Kara's ideas? If you do, then I hope that you will [contact](/contact/) me to
share some of your thoughts. Or, do you want to be updated when I publish new
interviews in this series? If you do, then please [subscribe](/support/) to my
mailing list.

:::

{{< include /_back-blog.qmd >}}
